version: "3.8"
services: 
  db:
    image: postgres:latest
    container_name: 'bd_postgres'
    ports: 
      - '5432:5432'
    restart: always
    environment: 
      POSTGRES_USER: 'postgres'
      POSTGRES_PASWORD: '123456'
      POSTGRES_DB: 'neoway'
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks: 
      - neoway-net
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/tb_dados_compra.sql:/docker-entrypoint-initdb.d/tb_dados_compra.sql
  
  web:
    build: .
    container_name: 'neoway-teste'
    ports: 
      - "4500:4500"
    depends_on: 
      - db
    networks: 
      - neoway-net

networks: 
  neoway-net:
    driver: bridge
